services:
  db:
    image: postgres:17
    container_name: bookstall_postgres_db
    environment:
      POSTGRES_DB: bookstall_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bookstall_postgres
    ports:
      - "9006:5432"   # host:container
    volumes:
      - postgres_data:/var/lib/postgresql/data  # persistent DB storage
  redis:
    image: redis:8
    container_name: bookstall_redis
    restart: always
    ports:
      - "9007:6379"  # expose Redis for debugging

  webapp1:
    build: . # build the image from the Dockerfile... Docker will look for a file named Dockerfile (default name) in that directory.
    # IMPORTANT: Even though you wrote build: . three times,
    # Docker doesnâ€™t rebuild the image three times.
    # It builds once (cached) and then uses that image for all three containers.
    container_name: bookstall_django_app_1
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    environment:
      - APP_NAME=bookstall_app_1
    volumes:
      - .:/bookstall_app      # mount your project for live reload
    ports:
      - "8003:8000"           # host:8003 -> container:8000
    depends_on:
      - db      # ensures Postgres starts first
  webapp2:
    build: . # build the image from the Dockerfile... Docker will look for a file named Dockerfile (default name) in that directory.
    container_name: bookstall_django_app_2
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    environment:
      - APP_NAME=bookstall_app_2
    volumes:
      - .:/bookstall_app      # mount your project for live reload
    ports:
      - "8004:8000"           # host:8004 -> container:8000
    depends_on:
      - db      # ensures Postgres starts first
  webapp3:
    build: . # build the image from the Dockerfile... Docker will look for a file named Dockerfile (default name) in that directory.
    container_name: bookstall_django_app_3
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    environment:
      - APP_NAME=bookstall_app_3
    volumes:
      - .:/bookstall_app      # mount your project for live reload
    ports:
      - "8005:8000"           # host:8005 -> container:8000
    depends_on:
      - db      # ensures Postgres starts first
  nginx:
    image: nginx:alpine
    container_name: nginx_load_balancer
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - webapp1
      - webapp2
      - webapp3

volumes:
  postgres_data:
  static_volume:
  media_volume: